pull_request_rules:
  - name: automatic develop for main when CI passes and 2 reviews and not WIP
    conditions:
      - check-success=build
      - check-success=Lint Code Base
      - base=develop
      - label!=work-in-progress
    actions:
      merge:
        method: merge
  - name: automatic merge for main when CI passes and 2 reviews and not WIP
    conditions:
      - check-success=build
      - check-success=Lint Code Base
      - base=master
    actions:
      merge:
        method: merge