name: Package Application with Pyinstaller

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: 

    - uses: actions/upload-artifact@v2
      with:
        name: hello_world
        path: dist/

    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: dist/hello_world
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
