name: Package Application with Pyinstaller

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - uses: actions/upload-artifact@v3
      with:
        name: hello_world
        path: src/dist

    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: dist/hello_world
        tag_name: ${{ github.ref }}
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
