name: Package Application

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull Objects
      uses: actions/checkout@v3

    - name: Make Package Directories
      run: |
        mkdir -p package/opt

    - name: Create Python Package
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - name: Copy Python Package
      run: |
        cp -r src/dist/linux/hello_world package/opt/hello_world

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.133.0
      with:
        ruby-version: 2.7

    - name: Install FPM
      run: |
        gem install fpm

    - name: Create Debian Package
      run: |
        fpm -C package -s dir -t deb -n "hello_world" -v 0.1.0 -p hello_world.deb

    - name: Upload Package Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hello_world
        path: hello_world.deb