name: Test Package Application

on:
  pull_request:
    branches: [ develop ]

jobs:
  TestPackageApplication:

    runs-on: ubuntu-latest

    steps:
    - name: Pull Objects
      uses: actions/checkout@v3

    - name: Make Package Directories
      run: |
        mkdir -p package/opt
        mkdir -p package/usr/share/applications
        mkdir -p package/usr/share/icons/hicolor/scalable/apps

    - name: Create Python Package
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - name: Copy Python Package
      run: |
        cp -r src/dist/linux/hello_world package/opt/hello_world
        cp src/icons/penguin.svg package/usr/share/icons/hicolor/scalable/apps/hello_world.svg
        cp src/hello_world.desktop package/usr/share/applications

    - name: Apply Permissions
      run: |
        find package/opt/hello_world -type f -exec chmod 644 -- {} +
        find package/opt/hello_world -type d -exec chmod 755 -- {} +
        find package/usr/share -type f -exec chmod 644 -- {} +
        chmod +x package/opt/hello_world

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.133.0
      with:
        ruby-version: 2.7

    - name: Install FPM
      run: |
        gem install fpm

    - name: Create Debian Package
      run: |
        fpm -C package -s dir -t deb -n "hello_world" -p hello_world.deb

    - name: Create RedHat/Fedora Package
      run: |
        fpm -C package -s dir -t rpm -n "hello_world" -p hello_world.rpm

    - name: Upload Package Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hello_world
        path: hello_world.*
